### ISSUE TITLE
Polevectors on legs flip when character is rotated upside down

### ISSUE THREAD

**Issue by remimcgill** [miquelcampos/mgear#10]
When we rotate the global control 180 so the character is upside down right at 180 the Polevectors on legs flip

**Comment by miquelcampos** [comment]
Hi Remi,

I can't reproduce the error here. I am rotating  global_c0_ctl to 180 in X axis. Also, I have try to rotate in other axis with no issues. Can you send me a sample scene?

Thanks,
Miquel

**Comment by remimcgill** [comment]
Yes I'll get an example file, thanks



On Thu, Dec 1, 2016 at 3:01 AM -0500, "Miquel Campos" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Remi,

I can't reproduce the error here. I am rotating global_c0_ctl to 180 in X axis. Also, I have try to rotate in other axis with no issues. Can you send me a sample scene?

Thanks,
Miquel

-

**Comment by miquelcampos** [comment]
Hi Remi,

Did you send me the sample scene for this issue?  I didn't receive anything.

Thanks,
Miquel

**Comment by miquelcampos** [comment]
can't replicate this issue
