### ISSUE TITLE
shifter:update guide structure in pre custom step

### ISSUE THREAD

**Issue by akiwoRM** [miquelcampos/mgear#101]
Hi, Miquel!

I want to build from separated some guide files.

for example:
- global guide file
- low body guide file
- facial guide file
- cloth parts guide file

import these files, parent to global guide and build.

I tried to use the pre custom step, but it didn't come out as I wanted.

That has already completed to find guide structure before executing the pre custom step.

The pre custom step is just script. It doesn't depend on shifter specification.
So even if change to execute timing, I think impact is small.

Cheers,

**Comment by miquelcampos** [comment]
I did a little test just for fun,
It is possible with a  little code refactor.
I will add this request to the following release since I am also interested in this functionality.

Meanwhile if you feel adventurous, here is the test snippet to change the functionality

Shifter/__init__.py

```python
def build(self):
        """Build the rig."""

        self.options = self.guide.values
        self.guides = self.guide.components

        self.customStepDic["mgearRun"] = self

        if not self.stopBuild:
            self.initialHierarchy()
            self.processComponents()
            self.finalize()
            self.postCustomStep()

            return self.model

    def stepsList(self, checker, attr):
        if self.options[checker]:
            return self.options[attr].split(",")
        else:
            return None

    def customStep(self, customSteps=None):
        if customSteps:
            for step in customSteps:
                if not self.stopBuild:
                    self.stopBuild = guide.helperSlots.runStep(
                        step.split("|")[-1][1:], self.customStepDic)
                else:
                    pm.displayWarning("Build Stopped")
                    break

    def preCustomStep(self):
        self.stopBuild = False
        selection = pm.ls(selection=True)
        if not selection:
            mgear.log(
                "Select one or more guide root or a guide model",
                mgear.sev_error)
            return
        if selection[0].hasAttr("ismodel") and \
                selection[0].attr("doPreCustomStep").get():
            customSteps = selection[0].attr("preCustomStep").get().split(",")
            self.customStep(customSteps)

    def postCustomStep(self):
        customSteps = self.stepsList("doPostCustomStep", "doPostCustomStep")
        self.customStep(customSteps)
```
###Use it at your own risk!

Cheers,
Miquel

**Comment by akiwoRM** [comment]
Thank you! :smile: 
I'll try to update by myself.

**Comment by miquelcampos** [comment]
I have implemented this.

Be careful with name clashing on imported/merged guides

**Comment by akiwoRM** [comment]
I tried this, but execute pre customstep command just by update guide.
Please check it.

**Comment by akiwoRM** [comment]
I tried this.
After all the pre custom step is executed, if guide root isn't selected, it fails to build.
