### ISSUE TITLE
Synoptic:It's not running synoptic

### ISSUE THREAD

**Issue by akiwoRM** [miquelcampos/mgear#107]
Now it's not running synoptic in develop branch.
Error message is the following.

\# Traceback (most recent call last):
\#   File "/marza/team/rnd/tools/maya/mGear/2.2.5/all/python/mgear/maya/synoptic/\_\_init\_\_.py", line 221, in updateTabs
\#     synoptic_tab = getattr(module, "SynopticTab")()
\#   File "/marza/team/rnd/tools/maya/mGear/2.2.5/all/python/mgear/maya/synoptic/tabs/biped/\_\_init\_\_.py", line 30, in \_\_init\_\_
\#     super(SynopticTab, self).\_\_init\_\_(self, parent)
\#   File "/marza/team/rnd/tools/maya/mGear/2.2.5/all/python/mgear/maya/synoptic/tabs/\_\_init\_\_.py", line 46, in \_\_init\_\_
\#     klass.connectMaya()
\#   File "/marza/team/rnd/tools/maya/mGear/2.2.5/all/python/mgear/maya/synoptic/tabs/\_\_init\_\_.py", line 90, in connectMaya
\#     gui = OpenMayaUI.MQtUtil.fullName(ptr)
\# TypeError: Expected argument of type long
\# Error: Synoptic tab: %s Loading fail biped
Expected argument of type long #

**Comment by miquelcampos** [comment]
looks like if an issue with the pointer to Maya main window. 

I don't have the issue in my side.  
Can you test with a clean copy of the repo locally?   
Are you in linux?  
If the clean copy fail in linux, can you try in windows, an let me know if is working?

Now we are vendoring QT.py and I remember I had to adjust some of the functions. Maybe this is related.

Thanks,
Miquel

**Comment by akiwoRM** [comment]
@gatgui tries to cast QtCompat.getCppPointer(self) return value to type long.
Now it's running.
I'm using linux, I don't try on windows. 
Thanks,

**Comment by miquelcampos** [comment]
@akiwoRM  Ok. I will close this issue. 
Please let me know if there is any other issue in the future. Thanks.
