### ISSUE TITLE
Maya exit with fatal error

### ISSUE THREAD

**Issue by zakuro9715** [miquelcampos/mgear#109]
Hi.

Maya exit with fatal error when I am testing mgear for my promotion project of school.
I don't know that it is bug of bug or bug of mgear.

This problem is arised with following steps:

1. Click component icon of Guides UI
2. Execute "Build from selection"
3. Undo
4. Click component icon of Guides UI

Environment:
- Win10 64bit
- Maya 2018

**Comment by miquelcampos** [comment]
Is  a known issue: https://github.com/miquelcampos/mgear/issues/72
Looks like is a pymel undo issue.  
The recommended workaround is to delete the generated rig instead of use "Undo"
