### ISSUE TITLE
Difficulty with duplicate names

### ISSUE THREAD

**Issue by remimcgill** [miquelcampos/mgear#11]
Hi, we're having some difficulty with the feature that extracts the control shapes for reapplication during building

The problem is that the names of the objects are exactly the same as the actual controls built so when we try to write scripts after that get a control by name we have trouble because there are two objects with exactly the same name but in two different hierarchies.  

E.G. More than one  Global Ctrl  found, rig|global_C0_ctl and controllers_org|global_C0_ctl

Perhaps we could put the copies of the controls in their own namespace? E.G.  controllers_org:global_C0_ctl

Thanks,
Remi

**Comment by miquelcampos** [comment]
Hi Remi,

Yes this is a known issue, but very easy to fix.  I will fixed for the next release.

Thanks,
Miquel

**Comment by miquelcampos** [comment]
This is fixed in the commit 68ddda10b4cae2c3a4938d2810ce0020f27c4f0d
