### ISSUE TITLE
Chain_01 IK refs not being connected

### ISSUE THREAD

**Issue by kolenicmi** [miquelcampos/mgear#13]
Chain components, when built, do create an IK ref enum attribute on the specified host, but that attribute isn't connected to anything. The problem is the addConnection() definition in chain_01.py. I found a way around it by stealing code from the leg component's code.

**Comment by miquelcampos** [comment]
Thank you for the feedback I will check it ASAP

Cheers,
Miquel

**Comment by miquelcampos** [comment]
Hi,

This issue is fixed in the commint 	9b8ea64   Is on the branch RB-2.1

Cheers,
Miquel
