### ISSUE TITLE
Synoptic update:

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#16]
-IK/FK Animation transfer
    -Support for leg_3jnt
    -Mirror and flip support for custom attr and  update LR mapping logic
    -Update keyall y select all widget to use any set

**Comment by yamahigashi** [comment]
Hi @miquelcampos ,
Is there any progress about `IK/FK Animation transfer` ? If not, I will take it.

**Comment by miquelcampos** [comment]
Hi @yamahigashi 
No, I didn't start yet on this. Right now, I am working on the channel wrangler and some bugs.
For the IK/FK animation transfer, you are welcome to do it. :)
I was thinking to do it similar to the space switcher. With options to transfer on keyframes and full bake for each frame.  But any idea or improvement is very welcome. Also for trigger the action/menu I was thinking to use the right click on the IK/FK switch button from the synoptic.
what is your idea?

Thanks,
Miquel

**Comment by yamahigashi** [comment]
Ok, i got it :)

> I was thinking to do it similar to the space switcher. With options to transfer on keyframes and full bake for each frame. 

I'm thinking so too,


>  Also for trigger the action/menu I was thinking to use the right click on the IK/FK switch button from the synoptic.

I will implement it like that, but it is a bit hard to understand at first look, so it may be better to arrange  a buttun just like space transfer's ▼.

**Comment by miquelcampos** [comment]
button with ▼ sounds good for me! :)
