### ISSUE TITLE
Export  FBX unity/Unreal

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#21]
-Check limits tool: Max influence limit for game engine export
    -half bake tool (local rigs to blendshape bake)

**Comment by milesckt** [comment]
Hi Miquel,

Do you plan to write a custom FBX exporter,or a bake tool or both?

Best,
Miles

**Comment by miquelcampos** [comment]
Yes, something to prepare de model and take care of the basic cleanup, anim bake and data consistency check.

**Comment by milesckt** [comment]
great
