### ISSUE TITLE
leg_3jnt_01 joint flipping problem

### ISSUE THREAD

**Issue by Lohult** [miquelcampos/mgear#236]
Hi Miquel,

I have discovered a bit of a flipping problem with the leg_3jnt_01 component.

The leg component has joints ranging from leg_L0_0_jnt through to leg_L0_9_jnt followed by leg_L0_end_jnt.

The flipping occurs when rotating leg_L0_ik_ctl in positive X. 91.068 is the exact number where the flip occurs (the guide is kept in default arrangement for the test).

At 91.068 rotation X on the IK control leg_L0_9_jnt and leg_L0_end_jnt flips from zero to -180. When skinning to these joints it becomes quite obvious when the flipping occurs.

My use case is a cat leg and the IK controller get rotated to curl the paw while walking for example.

**Comment by Lohult** [comment]
This problem can perhaps be fixed if the way the foot connects to the leg is setup in a way that it has a control that when rotated only affects the foot but when translated affects both ik effector and foot.

**Comment by miquelcampos** [comment]
Hi @Lohult  I will check this since I also have another bug in this component:
https://github.com/mgear-dev/shifter_classic_components/issues/4

Thanks for the feedback :)

**Comment by miquelcampos** [comment]
I moving this to the other repository https://github.com/mgear-dev/shifter_classic_components/issues/

**Comment by miquelcampos** [comment]
This issue was moved to mgear-dev/shifter_classic_components#11
