### ISSUE TITLE
mgear.maya.vector - getTransposedVector

### ISSUE THREAD

**Issue by Lohult** [miquelcampos/mgear#242]
Hi,
I'm not 100% if I'm using getTransposedVector(v, position0, position1, inverse=False) correctly but I keep getting a problem where I feed datatype.Vector's into position0 and position1 but getTransposedVector function then subtracts parts of it and stores it as a float after which it tries to use .normalize(). Problem is, that only works on dt.Vector type objects and not a raw float value. The problem persists later where .angle() is attempted but the same thing goes there, can't use it on a float value.

I tried rewriting it using datatype.VectorN but I'm afraid my experience limited the results and I am stuck.

Here is a snippet of the code:

```
def getTransposedVector(v, position0, position1, inverse=False):

    v0 = position0[1] - position0[0]
    # v0 is no longer a datatype.Vector but a pure float.
    v0.normalize()

    v1 = position1[1] - position1[0]
    # Same problem here
    v1.normalize()
    # Can't use angle.
    ra = v0.angle(v1)

    vector = rotateAlongAxis(v, axis, ra)

    return vector
```

Perhaps I am mistaken here? Cheers.

**Comment by Lohult** [comment]
I think this is a case of a user error. Feeding it two vector3's, one for position0 and one for position1 was my problem. If I feed it an array of two vector3 for both arguments. It seems to be working as per the example in the documentation.

**Comment by miquelcampos** [comment]
@Lohult  sorry for the super late reply. Glad that you found the solution. Just let me know if you need anything else in the future. I will try to reply faster :P

**Comment by Lohult** [comment]
@miquelcampos not to worry, thanks mate!
