### ISSUE TITLE
control_01 component maximum scale is too small.

### ISSUE THREAD

**Issue by Ruuttu** [miquelcampos/mgear#245]
We're making a ridiculously large character and the maximum scale of 200 for controls isn't enough. Part of the problem is we're using centimeters for units, so a ten meter character is already 1000 units. I'd like to bump the maximum scale to 2000 since there shouldn't be any harm in doing so.

I can make a pull request, but it's not clear to me where it should go :)

**Comment by miquelcampos** [comment]
Hi @Ruuttu 

I will copy this issue to shifter_classic_components repository and do the change for mgear 3.0

This repo is deprecated.   If you need this for mGear 2.X please do it in your fork/repository. I am not taking any pull request for this version (at less not planning :) )

**Comment by miquelcampos** [comment]
here is the new issue: https://github.com/mgear-dev/shifter_classic_components/issues/24
