### ISSUE TITLE
IK/FK Switch from synoptic

### ISSUE THREAD

**Issue by liorbenhorin** [miquelcampos/mgear#28]
Hi Miquel!
So, if you remember, when you spoke last time, i told you i will take a closer look at mGear while considering it as the main Rigger for a new very cool series im going to supervise on?
Anyways, im on it right now, and will probably call you very soon :), but before that i'm trying to learn as much as i can from the documentation and from the vimeo channel.

A small thing i encountered while testing the synoptic with the  basic biped rig is:
when trying to IK/FK switch:
```
# Traceback (most recent call last):
#   File "C:/Users/liorbh/Documents/maya/2015-x64/scripts\mgear\maya\synoptic\widgets.py", line 102, in mousePressEvent
#     syn_uti.ikFkMatch(model, ikfk_attr, uiHost_name, fk0, fk1, fk2, ik, upv)
# AttributeError: 'module' object has no attribute 'ikFkMatch'
```

which was solved by adding this to line 281 
```
def ikFkMatch(model, ikfk_attr, uiHost_name, fk0, fk1, fk2, ik, upv):
```
and then declaring: (What is the use of ikRot, the caller dose not send it) 
ikRot = None 
at the first line.

The other thing
When attempting to use the SpaceSwitcher, i got:
```
# Traceback (most recent call last):
#   File "C:/Users/liorbh/Documents/maya/2015-x64/scripts\mgear\maya\synoptic\utils.py", line 621, in doSpaceTransfer
#     for c in maya_main_window().children():
# NameError: global name 'maya_main_window' is not defined
```

Whic was solved by changing line 627
from
```
        for c in .maya_main_window().children():
```

to 
```
        for c in gqt.maya_main_window().children():
```

Am i getting it all wrong? :)

Best,
Talk soon,
Lior

**Comment by miquelcampos** [comment]
I just have checked this part. and looks a really silly bug when I have refactored some parts

I have updated the gqt. issue. 

The other one was fixed (and improved functionality) by Yamahigashi-san https://github.com/miquelcampos/mgear/pull/25
