### ISSUE TITLE
mGear Skinning Export Bug

### ISSUE THREAD

**Issue by kolenicmi** [miquelcampos/mgear#31]
Hi!
We ran into an interesting problem, in which the skinning export tool was intermittently failing to find the skinClusters on character geometry. It would give the error: "Skiped because don't have Skin Cluster"
I was able to narrow down the cause:
When geometry is skinned, the geo gets a new shape node. When referenced geometry is skinned, the shape node's name has "Deformed" added onto the end. The getSkinCluster() definition in mgear.skin.py takes this into account. However, when referenced geometry is skinned, and then the reference is imported, the "Deformed" suffix remains on the shape node, but the geo itself is no longer referenced. This is when the export problem would arise. Since the code checks whether the geo is referenced before taking the "Deformed" suffix into account, it would fail. 
I was able to get around it by simply checking whether the geometry's shape node has the "Deformed" suffix, regardless of whether it is referenced or not.

**Comment by miquelcampos** [comment]
Thank you for the feedback!
 I know this limitation and I will check your workaround to implement it as a default behavior.
