### ISSUE TITLE
3 point leg IK inverted when generating rig.

### ISSUE THREAD

**Issue by DavidRyatta** [miquelcampos/mgear#34]
I'm trying to fit the IK leg to a horse leg and when I generate the controllers the Ik seems to generate backwards and the foot control is oriented incorrectly and go a little insane when trying to move it.

As a side to this it would be nice to be able to have a 4 point leg option for animals that have 4 leg joints and create a curved IK to match skeletal structures better.

**Comment by miquelcampos** [comment]
Hello David,

Sorry for super late reply. I think this is fixed. Can you try with the latest develop branch?  Also if you can send me a sample scene will be awesome.

thanks,
Miqule
