### ISSUE TITLE
Request to add leg_3jnt Full IK parameter to the component settings

### ISSUE THREAD

**Issue by remimcgill** [miquelcampos/mgear#4]
Hi Miquel, we're using the 3 joint leg and we are wanting our rig to have only the two joints of the IK chain to be active when the rig is built.  

Currently we can change this after it has been built with the full 3 bone attribute, but we would like to be able to set this so that the character is always built this way.  The full IK works pretty well for a dog, but doesn't work very well for a horse for instance.

It may also be something to think about an additional option for the leg if not using the full IK to perhaps have the last segment aim at the root of the leg, so that it follows the body forward and backward, but as the body lowers it will not bend downward as a full IK chain would.

An additional possibility would be to add a 'clavicle' for the back leg like how the front leg has the shoulder.  This isn't anatomically correct but can often help avoid having the back quarters be too rigid

**Comment by miquelcampos** [comment]
Hi Remi,

Thank you for the feedback. I will  try to add this functionality for the next release.

Best regards,
Miquel

**Comment by miquelcampos** [comment]
Hi Remi, 
I guess is a little late :P but, finally this request is done.  It is available on the RB-2.1 branch now.  

Cheers,
Miquel
