### ISSUE TITLE
mGear getSkinCluster issue

### ISSUE THREAD

**Issue by akiwoRM** [miquelcampos/mgear#41]
There are cases to return wrong skinCluster node if using getSkinCluster function in skin module.

Currently, getSkinCluster function always returns skinCluster node which it was first found.
I think It's better to check which geometry name is right.

**Comment by miquelcampos** [comment]
Thank you for the feedback. I will check it ASAP.

**Comment by miquelcampos** [comment]
I have cherry picket your change.  Thank you.
