### ISSUE TITLE
Shifter: component UI min division hang. Check all components

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#42]
It looks like if I try to put in something lower than 3 in the spine divisions on my guide settings the UI will hang for a period of time.

**Comment by slegrand** [comment]
That happens with all divisions parameters btw not just the spine.

**Comment by miquelcampos** [comment]
So is time to review all :)  thanks again for the head up here!

**Comment by miquelcampos** [comment]
Hi @slegrand 
I have checked the issue but don,t hang for me. I will change the spine and neck to avoid the error message.

I have checked the arms and legs and looks OK. Where did you find the issue in other components? Can you be more specific when you say in all division parameters. Thanks :)

**Comment by slegrand** [comment]
Strange. For me it does it on every component that has a divisions number. It could be a Maya 2017 bug. I haven't updated to update 4 yet. maybe that will fix it. I'll let you know if I find the reason.

**Comment by miquelcampos** [comment]
@slegrand I am checking on Maya 2016.5 and 2018

For example the arm_2jnt_01 have this issue for you?

**Comment by miquelcampos** [comment]
Hi @slegrand 
I just did a push to fix the neck and spine.  I will close the issue. But I can open it again, if we find more issues in this topic. 

Thanks,
Miqule
