### ISSUE TITLE
mGear quadruped rig not being created in 2018

### ISSUE THREAD

**Issue by dramaqueen94** [miquelcampos/mgear#44]
the quadruped guide loads, but I can't create the rig when I click Build form Selection. Please help!

**Comment by dramaqueen94** [comment]
the script editor gives me this:

GEAR version : 2.2.1
None
= GEAR RIG SYSTEM ==============================================
Checking guide
Get options
Get controllers
Get components
Can't find parameter 'ctlGrp' in local_C0_root
local_C0 (control_01)
Can't find parameter 'ctlGrp' in body_C0_root
body_C0 (control_01)
Can't find parameter 'ctlGrp' in spine_C0_root
spine_C0 (spine_ik_01)
Can't find parameter 'ctlGrp' in neck_C0_root
neck_C0 (neck_ik_01)
Can't find parameter 'ctlGrp' in spineUI_C0_root
spineUI_C0 (control_01)
Can't find parameter 'ctlGrp' in headUI_C0_root
headUI_C0 (control_01)
Can't find parameter 'ctlGrp' in mouth_C0_root
mouth_C0 (mouth_01)
Can't find parameter 'ctlGrp' in eyeslook_C0_root
eyeslook_C0 (control_01)
Can't find parameter 'ctlGrp' in eye_L0_root
eye_L0 (eye_01)
Can't find parameter 'ctlGrp' in eye_R0_root
eye_R0 (eye_01)
Can't find parameter 'ctlGrp' in shoulder_L0_root
shoulder_L0 (chain_01)
Can't find parameter 'ctlGrp' in legFront_L0_root
legFront_L0 (leg_3jnt_01)
Can't find parameter 'ctlGrp' in footFront_L0_root
footFront_L0 (foot_bk_01)
Can't find parameter 'ctlGrp' in frontLegUI_L0_root
frontLegUI_L0 (control_01)
Can't find parameter 'ctlGrp' in shoulder_R0_root
shoulder_R0 (chain_01)
Can't find parameter 'ctlGrp' in legFront_R0_root
legFront_R0 (leg_3jnt_01)
Can't find parameter 'ctlGrp' in footFront_R0_root
footFront_R0 (foot_bk_01)
Can't find parameter 'ctlGrp' in frontLegUI_R0_root
frontLegUI_R0 (control_01)
Can't find parameter 'ctlGrp' in legBack_L0_root
legBack_L0 (leg_3jnt_01)
Can't find parameter 'ctlGrp' in footBack_L0_root
footBack_L0 (foot_bk_01)
Can't find parameter 'ctlGrp' in backLegUI_L0_root
backLegUI_L0 (control_01)
Can't find parameter 'ctlGrp' in legBack_R0_root
legBack_R0 (leg_3jnt_01)
Can't find parameter 'ctlGrp' in footBack_R0_root
footBack_R0 (foot_bk_01)
Can't find parameter 'ctlGrp' in backLegUI_R0_root
backLegUI_R0 (control_01)
The guide doesn't seem to be up to date. Check logged messages and update the guide.
Guide loaded from hierarchy in  [ 0:00:01.742000 ]

**Comment by miquelcampos** [comment]
Hi Thank you for logging the error here.

You can use the update guide command on the shifter menu. But I will update the default guide for the next release so is not needed to do it manually.

Thanks,
Miquel
