### ISSUE TITLE
Synoptic: Match IK/FK without split ctl for trans and rot.

### ISSUE THREAD

**Issue by hoover900** [miquelcampos/mgear#57]
Match IK/FK doest work on arms with combined ctl for rotation and translation.
The components affected are:

arm_2jnt_01
arm_2jnt_freeTangents_01

```
Can't` find object : arm_L0_ikRot_ctl
Can't find object : arm_L0_ikRot_mth
# Traceback (most recent call last):
#   File "C:\Users\mhanny\Documents\maya\2017\modules\mgear\scripts\mgear\maya\synoptic\widgets.py", line 136, in mousePressEvent
#     syn_uti.ikFkMatch(model, ikfk_attr, uiHost_name, fks, ik, upv, ikRot)
#   File "C:\Users\mhanny\Documents\maya\2017\modules\mgear\scripts\mgear\maya\synoptic\utils.py", line 463, in ikFkMatch
#     tra.matchWorldTransform(ikRotTarget, ikRotNode)
#   File "C:\Users\mhanny\Documents\maya\2017\modules\mgear\scripts\mgear\maya\transform.py", line 531, in matchWorldTransform
#     sWM = source.getMatrix(worldSpace=True)
# AttributeError: 'NoneType' object has no attribute 'getMatrix'
```

If I comment out lines 129, 130 of \mgear\scripts\mgear\maya\synoptic\widgets.py it works as expected, but then that clearly breaks iK arms with split controls. Would this be an issue with the component then?

**Comment by miquelcampos** [comment]
This is not a bug. The synoptic tab need to be updated to your new configuration. Is very simple. I will record a video when I have time. 

I keep the issue open as a reminder :)

**Comment by NachoSant** [comment]
Hi hoover900 and miquelcampos,

I had that issue another day and I was checking the script error, and seems that the match algorithm is trying match an object that not exist. I'm not sure but seems that the variable ikRot is filled or with true boolean, but well to faster fix, commenting the line 463 worked for me.

the file is in \mgear_2.2.4\scripts\mgear\maya\synoptic\utils.py
 
![image](https://user-images.githubusercontent.com/32291269/30847531-263b3c4e-a29c-11e7-945d-df410d396e74.png)

**Comment by miquelcampos** [comment]
Hi @hoover900   
This is a really brute force solution. But I guess it will work for you :)

I will record the video. But It will take at less 2 weeks more. Since I am really busy now 

Best regards,
Miquel
