### ISSUE TITLE
rigbits:createCTL function issue

### ISSUE THREAD

**Issue by akiwoRM** [miquelcampos/mgear#59]
I found misspelling in rigbits's __init__.py
Line 113, 117:
(F)rig_controlers_grp
(T)rig_controllers_grp

I think it's better to define special global object.
It's too hard coding.
Not only 'rig_controllers_grp', but also 'dagPose1'.

**Comment by miquelcampos** [comment]
Thank you @akiwoRM I will fix it ASAP
