### ISSUE TITLE
Shifter:leg_2jnts_freeTangents_01:no ikFoot in upvref attribute

### ISSUE THREAD

**Issue by akiwoRM** [miquelcampos/mgear#62]
Hi, Miguel.

I'm using leg_2jnts_freeTangents_01.
Compared with leg_2jnts_01, there is no ikFoot in upvref attribute.

**Comment by miquelcampos** [comment]
Hi @akiwoRM 

Thank you for the heads up here. I will add it :)

**Comment by akiwoRM** [comment]
Sorry, My repository's update was not enough.I hope you add my latest commit(
e8f0ea9).

**Comment by miquelcampos** [comment]
@akiwoRM sorry,  I am not sure if I understand your comment.  If your are in other branch you can cherry pick
