### ISSUE TITLE
Shifter: arm_2jnt_freeTangents_01  no attribute 'rollRef'

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#63]
I have a major problem when making rig that has guides for arm with free tangets. 
Everything works fine if I use arm_2jnt_01 however as soon as I use free tangent arm when building a rig I get an error "arm_2jnt_freeTangents_01\__init__.py line 692: 'Component' object has no attribute 'rollRef' # " and in rig group (after building it) everything seems to be unperented. 
It seems that I'm missing something.

**Comment by rewindthat** [comment]
This is the log i got from Maya 2016:

GEAR version : 2.2.4
None
= GEAR RIG SYSTEM ==============================================
Checking guide
Get options
Get controllers
Get components
local_C0 (control_01)
body_C0 (control_01)
spine_C0 (spine_ik_01)
spineUI_C0 (control_01)
shoulder_L0 (shoulder_01)
arm_L1 (arm_2jnt_freeTangents_01)
armUI_L0 (control_01)
meta_L0 (meta_01)
finger_L3 (chain_01)
finger_L2 (chain_01)
finger_L1 (chain_01)
finger_L0 (chain_01)
thumbRoll_L0 (control_01)
thumb_L0 (chain_01)
neck_C0 (neck_ik_01)
faceUI_C0 (control_01)
mouth_C0 (mouth_01)
tongue_C0 (chain_01)
eyeslook_C0 (control_01)
eye_R0 (eye_01)
eye_L0 (eye_01)
shoulder_R0 (shoulder_01)
arm_R1 (arm_2jnt_freeTangents_01)
armUI_R0 (control_01)
meta_R0 (meta_01)
finger_R3 (chain_01)
finger_R2 (chain_01)
finger_R1 (chain_01)
finger_R0 (chain_01)
thumbRoll_R0 (control_01)
thumb_R0 (chain_01)
leg_L0 (leg_2jnt_01)
foot_L0 (foot_bk_01)
legUI_L0 (control_01)
leg_R0 (leg_2jnt_01)
foot_R0 (foot_bk_01)
legUI_R0 (control_01)
Get parenting for: local_C0
Get parenting for: body_C0
Get parenting for: spine_C0
Get parenting for: spineUI_C0
Get parenting for: shoulder_L0
Get parenting for: arm_L1
Get parenting for: armUI_L0
Get parenting for: meta_L0
Get parenting for: finger_L3
Get parenting for: finger_L2
Get parenting for: finger_L1
Get parenting for: finger_L0
Get parenting for: thumbRoll_L0
Get parenting for: thumb_L0
Get parenting for: neck_C0
Get parenting for: faceUI_C0
Get parenting for: mouth_C0
Get parenting for: tongue_C0
Get parenting for: eyeslook_C0
Get parenting for: eye_R0
Get parenting for: eye_L0
Get parenting for: shoulder_R0
Get parenting for: arm_R1
Get parenting for: armUI_R0
Get parenting for: meta_R0
Get parenting for: finger_R3
Get parenting for: finger_R2
Get parenting for: finger_R1
Get parenting for: finger_R0
Get parenting for: thumbRoll_R0
Get parenting for: thumb_R0
Get parenting for: leg_L0
Get parenting for: foot_L0
Get parenting for: legUI_L0
Get parenting for: leg_R0
Get parenting for: foot_R0
Get parenting for: legUI_R0
Guide loaded from hierarchy in  [ 0:00:07.096000 ]
Initial Hierarchy
Init : local_C0 (control_01)
Init : body_C0 (control_01)
Init : spine_C0 (spine_ik_01)
Init : spineUI_C0 (control_01)
Init : shoulder_L0 (shoulder_01)
Init : arm_L1 (arm_2jnt_freeTangents_01)
Init : armUI_L0 (control_01)
Init : meta_L0 (meta_01)
Init : finger_L3 (chain_01)
Init : finger_L2 (chain_01)
Init : finger_L1 (chain_01)
Init : finger_L0 (chain_01)
Init : thumbRoll_L0 (control_01)
Init : thumb_L0 (chain_01)
Init : neck_C0 (neck_ik_01)
Init : faceUI_C0 (control_01)
Init : mouth_C0 (mouth_01)
Init : tongue_C0 (chain_01)
Init : eyeslook_C0 (control_01)
Init : eye_R0 (eye_01)
Init : eye_L0 (eye_01)
Init : shoulder_R0 (shoulder_01)
Init : arm_R1 (arm_2jnt_freeTangents_01)
Init : armUI_R0 (control_01)
Init : meta_R0 (meta_01)
Init : finger_R3 (chain_01)
Init : finger_R2 (chain_01)
Init : finger_R1 (chain_01)
Init : finger_R0 (chain_01)
Init : thumbRoll_R0 (control_01)
Init : thumb_R0 (chain_01)
Init : leg_L0 (leg_2jnt_01)
Init : foot_L0 (foot_bk_01)
Init : legUI_L0 (control_01)
Init : leg_R0 (leg_2jnt_01)
Init : foot_R0 (foot_bk_01)
Init : legUI_R0 (control_01)
Objects : local_C0 (control_01)
Objects : body_C0 (control_01)
Objects : spine_C0 (spine_ik_01)
Objects : spineUI_C0 (control_01)
Objects : shoulder_L0 (shoulder_01)
Objects : arm_L1 (arm_2jnt_freeTangents_01)
Objects : armUI_L0 (control_01)
Objects : meta_L0 (meta_01)
Objects : finger_L3 (chain_01)
Objects : finger_L2 (chain_01)
Objects : finger_L1 (chain_01)
Objects : finger_L0 (chain_01)
Objects : thumbRoll_L0 (control_01)
Objects : thumb_L0 (chain_01)
Objects : neck_C0 (neck_ik_01)
Objects : faceUI_C0 (control_01)
Objects : mouth_C0 (mouth_01)
Objects : tongue_C0 (chain_01)
Objects : eyeslook_C0 (control_01)
Objects : eye_R0 (eye_01)
Objects : eye_L0 (eye_01)
Objects : shoulder_R0 (shoulder_01)
Objects : arm_R1 (arm_2jnt_freeTangents_01)
Objects : armUI_R0 (control_01)
Objects : meta_R0 (meta_01)
Objects : finger_R3 (chain_01)
Objects : finger_R2 (chain_01)
Objects : finger_R1 (chain_01)
Objects : finger_R0 (chain_01)
Objects : thumbRoll_R0 (control_01)
Objects : thumb_R0 (chain_01)
Objects : leg_L0 (leg_2jnt_01)
Objects : foot_L0 (foot_bk_01)
Objects : legUI_L0 (control_01)
Objects : leg_R0 (leg_2jnt_01)
Objects : foot_R0 (foot_bk_01)
Objects : legUI_R0 (control_01)
Properties : local_C0 (control_01)
Properties : body_C0 (control_01)
Properties : spine_C0 (spine_ik_01)
Properties : spineUI_C0 (control_01)
Properties : shoulder_L0 (shoulder_01)
Properties : arm_L1 (arm_2jnt_freeTangents_01)
Properties : armUI_L0 (control_01)
Properties : meta_L0 (meta_01)
Properties : finger_L3 (chain_01)
Properties : finger_L2 (chain_01)
Properties : finger_L1 (chain_01)
Properties : finger_L0 (chain_01)
Properties : thumbRoll_L0 (control_01)
Properties : thumb_L0 (chain_01)
Properties : neck_C0 (neck_ik_01)
Properties : faceUI_C0 (control_01)
Properties : mouth_C0 (mouth_01)
Properties : tongue_C0 (chain_01)
Properties : eyeslook_C0 (control_01)
Properties : eye_R0 (eye_01)
Properties : eye_L0 (eye_01)
Properties : shoulder_R0 (shoulder_01)
Properties : arm_R1 (arm_2jnt_freeTangents_01)
Properties : armUI_R0 (control_01)
Properties : meta_R0 (meta_01)
Properties : finger_R3 (chain_01)
Properties : finger_R2 (chain_01)
Properties : finger_R1 (chain_01)
Properties : finger_R0 (chain_01)
Properties : thumbRoll_R0 (control_01)
Properties : thumb_R0 (chain_01)
Properties : leg_L0 (leg_2jnt_01)
Properties : foot_L0 (foot_bk_01)
Properties : legUI_L0 (control_01)
Properties : leg_R0 (leg_2jnt_01)
Properties : foot_R0 (foot_bk_01)
Properties : legUI_R0 (control_01)
Operators : local_C0 (control_01)
Operators : body_C0 (control_01)
Operators : spine_C0 (spine_ik_01)
Operators : spineUI_C0 (control_01)
Operators : shoulder_L0 (shoulder_01)
Operators : arm_L1 (arm_2jnt_freeTangents_01)
Operators : armUI_L0 (control_01)
Operators : meta_L0 (meta_01)
Operators : finger_L3 (chain_01)
Operators : finger_L2 (chain_01)
Operators : finger_L1 (chain_01)
Operators : finger_L0 (chain_01)
Operators : thumbRoll_L0 (control_01)
Operators : thumb_L0 (chain_01)
Operators : neck_C0 (neck_ik_01)
Operators : faceUI_C0 (control_01)
Operators : mouth_C0 (mouth_01)
Operators : tongue_C0 (chain_01)
Operators : eyeslook_C0 (control_01)
Operators : eye_R0 (eye_01)
Operators : eye_L0 (eye_01)
Operators : shoulder_R0 (shoulder_01)
Operators : arm_R1 (arm_2jnt_freeTangents_01)
Operators : armUI_R0 (control_01)
Operators : meta_R0 (meta_01)
Operators : finger_R3 (chain_01)
Operators : finger_R2 (chain_01)
Operators : finger_R1 (chain_01)
Operators : finger_R0 (chain_01)
Operators : thumbRoll_R0 (control_01)
Operators : thumb_R0 (chain_01)
Operators : leg_L0 (leg_2jnt_01)
Operators : foot_L0 (foot_bk_01)
Operators : legUI_L0 (control_01)
Operators : leg_R0 (leg_2jnt_01)
Operators : foot_R0 (foot_bk_01)
Operators : legUI_R0 (control_01)
Connect : local_C0 (control_01)
Connect : body_C0 (control_01)
Connect : spine_C0 (spine_ik_01)
Connect : spineUI_C0 (control_01)
Connect : shoulder_L0 (shoulder_01)
Connect : arm_L1 (arm_2jnt_freeTangents_01)
# Error: AttributeError: file C:\Users\Samo\Documents\mgear\scripts\mgear\maya\shifter\component\arm_2jnt_freeTangents_01\__init__.py line 692: 'Component' object has no attribute 'rollRef' #

**Comment by miquelcampos** [comment]
Thank you for the log. Can you also send me the guide file?  Please use wetransfer or dropbox download link.

Thanks!

**Comment by miquelcampos** [comment]
@rewindthat Hello again. I have found and fixed the issue in the latest commit. Thank you for the the feedback.  :)

**Comment by rewindthat** [comment]
Your welcome, mGear is awesome!!! Thank you for sharing.
