### ISSUE TITLE
Shifter: Change Global_C0_ctl to World_ctl

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#66]
We will add global_C0_ctl in the guide. This way we can add global_C0_ctl as a space refence.

**Comment by gatgui** [comment]
This break compatibility for animation files, this should go in 3.0 roadmap if ever

**Comment by miquelcampos** [comment]
Is not breaking compatibility. You can add the global_C0_ctl. In the guide

Check the new biped guide.

I will document this better. :)

**Comment by gatgui** [comment]
After the updates, all our build scripts failed because of the renaming.

**Comment by gatgui** [comment]
And published published animation couldn't apply because of the controller name

**Comment by miquelcampos** [comment]
Ok, I see. I will make this optional and off by default.

**Comment by miquelcampos** [comment]
Now this is an optional setting: **The old guide should be updated using the command**

The new checkbox have a little documentation if you hover the mouse on top

![image](https://user-images.githubusercontent.com/1050212/33369060-ca929806-d536-11e7-8883-67b0c2592da4.png)

**Comment by gatgui** [comment]
thinks man

**Comment by gatgui** [comment]
*thanks*

**Comment by miquelcampos** [comment]
You are welcome. :)  

@akiwoRM : Remember to update the guide in order to add the new option

**Comment by akiwoRM** [comment]
Thank you. I see.
