### ISSUE TITLE
Shifter: Control_01: Add option to have mirror behaviour

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#68]
We need an optional mirror behavior on L and R side.  Now we have some mirror but not correct in all axis

**Comment by miquelcampos** [comment]
Need a little more test and consolidate in control_01. Now still in control_02 because Maya 2018.1 bug with the translation tool when the object have negative scaling.

**Comment by miquelcampos** [comment]
TODO: Consolidate in one component

**Comment by akiwoRM** [comment]
I tried to create control_01 component.
But it fails to do.
The error message is the following .

\# Error: AttributeError: file /mGear/2.2.5/all/python/mgear/maya/shifter/component/control_01/settingsUI.py line 186: 'module' object has no attribute 'SIGNAL' #

**Comment by miquelcampos** [comment]
I have fixed this today: https://github.com/miquelcampos/mgear/commit/ff7362d928fee457fa61cef9afd3b228f44f5d85
