### ISSUE TITLE
mGear: IO curves

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#76]
Module to handle export import Nurb curves to json format.
-Must contemplate various shapes
-Color by index and RGB
-Curve shapes preset manages. A library of shapes

NOTE for Miquel: Update shifter control extract after finish this ticket

**Comment by csaez** [comment]
Is this open for anyone or are you already working on it?
Seems like an easy one to get into mgear and I was thinking on giving it a try :)

**Comment by miquelcampos** [comment]
Oh!!  OK no worries :)   Just remember the door is open any time ;)

PD: Normalmente me lo asigno todo a mi, por mala costumbre. Realmente no tendría que hacerlo hasta que empiece con el ticket/issue :P
