### ISSUE TITLE
mGear: Attribute: addAttribute not setting default attribute value.

### ISSUE THREAD

**Issue by Lohult** [miquelcampos/mgear#84]
The addAttribute function does not set attribute default values correctly at the moment:
`if value is not None: node.setAttr(longName, value)`
Since you can't set a default value after creating an attribute you need to set it at creation time. At the moment I made a hotfix that sets a condition to unpack "defaultValue" along with the other settings in the data variable:
`if type(value) is float or type(value) is int:
        data["defaultValue"] = float(value)`

This is by no means the solution because default values are not always float data types but it serves as an example. Thanks.

**Comment by miquelcampos** [comment]
Thank you for the feedback. I will review this issue ASAP

**Comment by mottosso** [comment]
> Since you can't set a default value after creating an attribute you need to set it at creation time.

Actually you can set default values on already created attributes, by using the `addAttr` in "edit mode".

```python
from maya import cmds
cmds.addAttr("mynode.myattr", edit=True, defaultValue=5.0)
```

- [Reference](http://help.autodesk.com/cloudhelp/2015/ENU/Maya-Tech-Docs/CommandsPython/addAttr.html#flagdefaultValue)

**Comment by Lohult** [comment]
@mottosso I stand corrected. However, currently the mgear API does not seem do that:
```
if value is not None:
        node.setAttr(longName, value)
```
it will probably then have to be
```
if value is not None:
        node.setAttr(longName, edit=True, value)
```
Thanks, this will be a much quicker fix.

**Comment by miquelcampos** [comment]
Hello,

I have modify the addAttribute function to set default values on numeric attributes. 
Also I will add some extra function to help the default attributes managment

TO DO:

add getDefaultValue:  I don't like the attributeQuery default function
add reset to default value function
add reset selected channels
edit mGear_resetSRT hotkey to support default values

@Lohult Can you test the change and let me know if is working for you?

Thanks for the feedback!

**Comment by miquelcampos** [comment]
@Lohult This is done! :) check the latest commit for more info
